version: 2
jobs:
  unit:
    docker:
      - image: fishtownjacob/test-container
    steps:
      - checkout
      - run: tox -e flake8,unit

  integration:
    docker:
      - image: fishtownjacob/test-container
    steps:
      - checkout

      - run:
          name: Checkout test project
          command: git clone https://github.com/fishtown-analytics/dbt-integration-tests.git

      - run:
          name: "Setup credentials"
          command: mkdir -p ~/.dbt/ && cp ~/project/test/integration/profiles.yml ~/.dbt/profiles.yml

      - run:
          name: Run integration tests
          command: tox -e integration
          no_output_timeout: 1h

      - store_artifacts:
          path: ./logs

workflows:
  version: 2
  test-everything:
    jobs:
      - unit
      - integration:
          requires:
            - unit
